PANDALS = [
    dict(id='bagbazar',name='Bagbazar Sarbojanin',name_bn='বাগবাজার সর্বজনীন',area='Bagbazar',area_bn='বাগবাজার',zone='North',lat=22.6045,lng=88.3655,type='Heritage',description='A beloved North Kolkata institution. Traditional ekchala idols, an old-world community spirit, and the timeless beauty of Bengali Pujo.',description_bn='উত্তর কলকাতার ঐতিহ্যবাহী পুজো। একচালার প্রতিমা ও আন্তরিক উৎসবের আবহে বাংলার চিরন্তন পুজোর স্বাদ।',metro='Shyambazar',metro_bn='শ্যামবাজার',best_time='Morning'),
    dict(id='kumartuli',name='Kumartuli Park',name_bn='কুমোরটুলি পার্ক',area='Kumartuli',area_bn='কুমোরটুলি',zone='North',lat=22.6002,lng=88.3618,type='Art & craft',description='In the neighbourhood where the goddess takes shape. Pair your visit with a respectful walk past the clay-idol workshops.',description_bn='যেখানে মাটির প্রতিমায় মায়ের রূপ ফুটে ওঠে। শিল্পীদের অনুমতি নিয়ে কুমোরটুলির কর্মশালাও ঘুরে দেখুন।',metro='Sovabazar Sutanuti',metro_bn='শোভাবাজার সুতানুটি',best_time='Morning'),
    dict(id='sovabazar',name='Sovabazar Rajbari',name_bn='শোভাবাজার রাজবাড়ি',area='Sovabazar',area_bn='শোভাবাজার',zone='North',lat=22.5965,lng=88.3654,type='Heritage',description='An intimate encounter with a historic bonedi-bari Puja. Visit respectfully; family rituals and access differ from public pandals.',description_bn='বনেদি বাড়ির ঐতিহ্যবাহী দুর্গাপুজো। পারিবারিক রীতিনীতি এবং প্রবেশের নিয়ম মেনে দর্শন করুন।',metro='Sovabazar Sutanuti',metro_bn='শোভাবাজার সুতানুটি',best_time='Morning'),
    dict(id='college-square',name='College Square',name_bn='কলেজ স্কোয়ার',area='College Street',area_bn='কলেজ স্ট্রিট',zone='Central',lat=22.5735,lng=88.3637,type='Illumination',description='A festival of reflections. The illuminated pandal across the lake creates one of Kolkata’s most atmospheric Puja views.',description_bn='জলের বুকে আলোর উৎসব। দীঘির জলে আলোকিত মণ্ডপের প্রতিফলন কলকাতার পুজোর এক অনন্য দৃশ্য।',metro='Mahatma Gandhi Road',metro_bn='মহাত্মা গান্ধী রোড',best_time='Evening'),
    dict(id='mohammad-ali',name='Mohammad Ali Park',name_bn='মহম্মদ আলি পার্ক',area='Chittaranjan Avenue',area_bn='চিত্তরঞ্জন অ্যাভিনিউ',zone='Central',lat=22.5791,lng=88.3583,type='Art & craft',description='Ambitious architecture and a central-city favourite. Combine it with College Square for an easy neighbourhood trail.',description_bn='স্থাপত্যের অভিনব ভাবনা ও মধ্য কলকাতার জনপ্রিয় পুজো। কলেজ স্কোয়ারের সঙ্গে একসঙ্গে ঘুরে দেখুন।',metro='Mahatma Gandhi Road',metro_bn='মহাত্মা গান্ধী রোড',best_time='Evening'),
    dict(id='santosh-mitra',name='Santosh Mitra Square',name_bn='সন্তোষ মিত্র স্কোয়ার',area='Bowbazar',area_bn='বৌবাজার',zone='Central',lat=22.5657,lng=88.3678,type='Art & craft',description='A spectacular large-scale community Puja known for elaborate themes. Allow extra time for queues and crowd diversions.',description_bn='বৃহৎ থিমের জন্য পরিচিত সর্বজনীন পুজো। দর্শনার্থীদের ভিড় ও পথ পরিবর্তনের জন্য বাড়তি সময় রাখুন।',metro='Central',metro_bn='সেন্ট্রাল',best_time='Morning'),
    dict(id='ekdalia',name='Ekdalia Evergreen',name_bn='একডালিয়া এভারগ্রিন',area='Ballygunge',area_bn='বালিগঞ্জ',zone='South',lat=22.5203,lng=88.3661,type='Heritage',description='Temple-inspired grandeur meets traditional worship. A lovely starting point for South Kolkata’s Puja circuit.',description_bn='মন্দিরের অনুপ্রেরণায় মণ্ডপ ও ঐতিহ্যবাহী প্রতিমা। দক্ষিণ কলকাতার পুজো পরিক্রমার চমৎকার সূচনা।',metro='Kalighat',metro_bn='কালীঘাট',best_time='Evening'),
    dict(id='ballygunge-cultural',name='Ballygunge Cultural',name_bn='বালিগঞ্জ কালচারাল',area='Southern Avenue',area_bn='সাদার্ন অ্যাভিনিউ',zone='South',lat=22.5161,lng=88.3571,type='Art & craft',description='Thoughtful installations with a strong neighbourhood heart. Walk nearby lanes to discover smaller celebrations too.',description_bn='শিল্পভাবনা ও পাড়ার আন্তরিকতার মেলবন্ধন। পাশের গলিতেও ছোট ছোট পুজোর আনন্দ খুঁজে নিন।',metro='Kalighat',metro_bn='কালীঘাট',best_time='Morning'),
    dict(id='tridhara',name='Tridhara Sammilani',name_bn='ত্রিধারা সম্মিলনী',area='Deshapriya Park',area_bn='দেশপ্রিয় পার্ক',zone='South',lat=22.5186,lng=88.3539,type='Art & craft',description='Contemporary art, immersive themes, and meticulous detail. Take your time looking at the work beyond the idol.',description_bn='সমকালীন শিল্প, থিম ও সূক্ষ্ম কাজের সমাহার। প্রতিমার পাশাপাশি মণ্ডপের শিল্পকর্মও মন দিয়ে দেখুন।',metro='Kalighat',metro_bn='কালীঘাট',best_time='Morning'),
    dict(id='suruchi',name='Suruchi Sangha',name_bn='সুরুচি সংঘ',area='New Alipore',area_bn='নিউ আলিপুর',zone='South',lat=22.5100,lng=88.3334,type='Art & craft',description='Celebrating regional art and storytelling through inventive pandals. A highlight of the New Alipore trail.',description_bn='আঞ্চলিক শিল্প ও কাহিনির উদ্ভাবনী মণ্ডপ। নিউ আলিপুরের পুজো পরিক্রমার অন্যতম আকর্ষণ।',metro='Rabindra Sarobar',metro_bn='রবীন্দ্র সরোবর',best_time='Morning'),
    dict(id='chetla',name='Chetla Agrani',name_bn='চেতলা অগ্রণী',area='Chetla',area_bn='চেতলা',zone='South',lat=22.5163,lng=88.3398,type='Art & craft',description='Dramatic art direction and a strong local following. Combine with Suruchi Sangha; expect busy evening approaches.',description_bn='নাটকীয় শিল্পভাবনা ও পাড়ার আবেগ। সুরুচি সংঘের সঙ্গে ঘুরে দেখুন; সন্ধ্যায় ভিড় হতে পারে।',metro='Kalighat',metro_bn='কালীঘাট',best_time='Morning'),
    dict(id='sreebhumi',name='Sreebhumi Sporting Club',name_bn='শ্রীভূমি স্পোর্টিং ক্লাব',area='Lake Town',area_bn='লেক টাউন',zone='East',lat=22.6004,lng=88.4024,type='Illumination',description='Known for monumental themed structures and dazzling illumination. Check local traffic advisories before travelling.',description_bn='বিরাট থিম মণ্ডপ ও অসাধারণ আলোকসজ্জার জন্য বিখ্যাত। যাওয়ার আগে স্থানীয় ট্রাফিক নির্দেশিকা দেখুন।',metro='Belgachia + local connection',metro_bn='বেলগাছিয়া ও স্থানীয় যান',best_time='Morning'),
]

DATES = [
    {'id':'mahalaya','day':'10','month':'OCT','name':'Mahalaya','name_bn':'মহালয়া','date':'2026-10-10','description':'The first light of Devi Paksha. Wake before dawn for the iconic Mahishasuramardini broadcast.','description_bn':'দেবীপক্ষের সূচনা। ভোরের মহিষাসুরমর্দিনী শুনে মাকে স্বাগত জানান।'},
    {'id':'shashthi','day':'16–17','month':'OCT','name':'Maha Shashthi','name_bn':'মহাষষ্ঠী','date':'2026-10-16','description':'Bodhan: the ceremonial awakening. The goddess is welcomed into her earthly home. Observance varies by panjika.','description_bn':'বোধন ও আমন্ত্রণে মায়ের আবাহন। পঞ্জিকা অনুযায়ী দিন ভিন্ন হতে পারে।'},
    {'id':'saptami','day':'17–18','month':'OCT','name':'Maha Saptami','name_bn':'মহাসপ্তমী','date':'2026-10-18','description':'Nabapatrika Snan at dawn, followed by the first full day of worship. Check the local pandal schedule.','description_bn':'ভোরে নবপত্রিকা স্নান, তারপর পুজোর মূল আচার। স্থানীয় মণ্ডপের সময়সূচি জেনে নিন।'},
    {'id':'ashtami','day':'19','month':'OCT','name':'Maha Ashtami','name_bn':'মহাষ্টমী','date':'2026-10-19','description':'Flowers in folded hands. Pushpanjali and the sacred transition of Sandhi Puja; confirm ritual times locally.','description_bn':'পুষ্পাঞ্জলি ও পবিত্র সন্ধিপুজো। আচারের নির্দিষ্ট সময় স্থানীয় মণ্ডপে জেনে নিন।'},
    {'id':'navami','day':'20','month':'OCT','name':'Maha Navami','name_bn':'মহানবমী','date':'2026-10-20','description':'A day of aarti, shared bhog, and one more evening of wonder before the farewell.','description_bn':'আরতি, ভোগ ও বিদায়ের আগের শেষ সন্ধ্যার আনন্দ।'},
    {'id':'dashami','day':'21','month':'OCT','name':'Vijaya Dashami','name_bn':'বিজয়া দশমী','date':'2026-10-21','description':'Sindoor Khela and immersion. A bittersweet farewell, carrying the promise: Asche bochor abar hobe.','description_bn':'সিঁদুরখেলা ও বিসর্জন। বিষণ্ণ বিদায়ের মাঝেও প্রতিশ্রুতি—আসছে বছর আবার হবে।'},
]