import React,{useState,useEffect,useCallback,Component} from 'react';
import {useMotionPreference} from '../hooks/useMotionPreference';
import {ArrowUpRight,Sun,RotateCcw,Flower2,Move,MousePointer2,X,Check,Maximize,Minimize,Pause,Play,Eye} from 'lucide-react';
import {useApp,tone} from '../context';
import {PageIntro} from '../components/shared';
import {Sanctuary} from '../components/Sanctuary';
import {Button} from '../components/ui/button';
import './Experience.css';
const discoveries={
 idol:['The goddess, in every detail','প্রতিটি খুঁটিনাটিতে দেবী','The shrine’s photograph honours the extraordinary craft of Durga idols. The many arms express divine strength; her serene gaze offers reassurance. This virtual sanctuary is an artistic interpretation, not a replica of a real pandal.','মণ্ডপের ছবি দুর্গাপ্রতিমার অনন্য শিল্পকে সম্মান জানায়। বহু হাত মহাশক্তির প্রকাশ, শান্ত দৃষ্টিতে আশ্বাস। এটি শৈল্পিক ভার্চুয়াল মণ্ডপ, বাস্তব মণ্ডপের প্রতিরূপ নয়।'],
 craft:['A city built by hand','হাতে গড়া শহর','Notice the fluted terracotta columns, the folds of vermilion cloth, and the marigold toran above the entrance. In real pandals, countless patient hands transform simple materials into extraordinary temporary worlds.','খেয়াল করুন পোড়ামাটির স্তম্ভের খাঁজ, লাল কাপড়ের ভাঁজ ও প্রবেশদ্বারের গাঁদা ফুলের তোরণ। বাস্তব মণ্ডপে অগণিত শিল্পীর হাতে সাধারণ উপাদান হয়ে ওঠে অসাধারণ জগৎ।'],
 lamp:['A flame, a moment of stillness','এক শিখায় প্রশান্তি','The brass pradip holds a small offering of light. Beside the altar, a thali of sweets, a conch, flowers, and a ritual vessel evoke the care of preparation. These digital arrangements are symbolic; local practices vary.','পিতলের প্রদীপে আলোর ছোট নিবেদন। বেদির পাশে মিষ্টির থালা, শঙ্খ, ফুল ও মঙ্গলঘটে ফুটে ওঠে যত্নের আয়োজন। ডিজিটাল এই বিন্যাস প্রতীকী; স্থানীয় প্রথা ভিন্ন হতে পারে।'],
};
class CanvasBoundary extends Component {
 state={error:false};static getDerivedStateFromError(){return {error:true};}
 render(){const {t}=this.props;return this.state.error?<div className="webgl-fallback" data-testid="webgl-error"><Flower2/><h2>{t('Your browser could not open the 3D sanctuary.','আপনার ব্রাউজারে ত্রিমাত্রিক মণ্ডপ খোলা যায়নি।')}</h2><p>{t('WebGL support is needed. You can still enjoy our gallery and stories.','ওয়েবজিএল প্রয়োজন। আমাদের চিত্রশালা ও গল্পগুলি দেখতে পারেন।')}</p><a href="/gallery" data-testid="webgl-gallery">{t('Visit the gallery','চিত্রশালায় চলুন')} ↗</a></div>:this.props.children;}
}
export default function Experience(){
 const {t,sound}=useApp(),reducedMotion=useMotionPreference();
 const [inside,setInside]=useState(false),[lit,setLit]=useState(true),[offered,setOffered]=useState(false),[discovered,setDiscovered]=useState([]),[info,setInfo]=useState(null),[expanded,setExpanded]=useState(false),[sceneKey,setSceneKey]=useState(0),[view,setView]=useState('altar'),[motionEnabled,setMotionEnabled]=useState(true),[ready,setReady]=useState(false);
 const markReady=useCallback(()=>setReady(true),[]);
 const enter=()=>{setInside(v=>!v);setView('altar');setInfo(null);};
 const discover=id=>{setInfo(id);setDiscovered(prev=>prev.includes(id)?prev:[...prev,id]);if(sound)tone();};
 const reset=()=>{setInside(false);setLit(true);setOffered(false);setInfo(null);setDiscovered([]);setView('altar');setReady(false);setSceneKey(k=>k+1);};
 useEffect(()=>{if(!expanded)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const escape=e=>{if(e.key==='Escape')setExpanded(false);};window.addEventListener('keydown',escape);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',escape);};},[expanded]);
 return <div className="experience-page">
  <PageIntro chapter={t('THE IMMERSIVE PANDAL / A DIGITAL HOMECOMING','ভার্চুয়াল মণ্ডপ / ডিজিটাল আগমন')} title={t('A world away.','দূরের পৃথিবী।')} italic={t('One step inside.','এক পা ভিতরে।')} description={t('Carved earth. The warmth of brass. Incense rising with a quiet offering. Enter a little world of devotion, brought to life.','খোদাই করা মাটি। পিতলের উষ্ণতা। নীরব নিবেদনে ধুনোর ধোঁয়া। জীবন্ত ভক্তির এক ছোট্ট জগতে প্রবেশ করুন।')}/>
  <section className={`experience-frame ${expanded?'expanded':''}`} data-testid="experience-frame" data-scene-ready={ready?'true':'false'}>
   <div className="experience-topbar"><span data-testid="experience-location"><i/>{t(inside?'THE INNER SANCTUARY':'AT THE THRESHOLD',inside?'গর্ভগৃহে':'প্রবেশদ্বারে')}</span><span data-testid="discovery-count">{String(discovered.length).padStart(2,'0')} / 03 {t('DISCOVERED','আবিষ্কৃত')}</span><button data-testid="expand-sanctuary" onClick={()=>setExpanded(!expanded)} aria-label={t(expanded?'Minimize sanctuary':'Expand sanctuary',expanded?'ছোট করুন':'পূর্ণ পর্দায় দেখুন')}>{expanded?<Minimize size={17}/>:<Maximize size={17}/>}</button></div>
   <div className="sanctuary-canvas" data-testid="sanctuary-canvas" data-lenis-prevent>
    <CanvasBoundary t={t}><Sanctuary key={sceneKey} inside={inside} lit={lit} offered={offered} onDiscover={discover} onEnter={enter} t={t} view={view} motionEnabled={motionEnabled} reducedMotion={!!reducedMotion} onReady={markReady}/></CanvasBoundary>
    {inside&&<div className="sanctuary-view-switcher" data-testid="sanctuary-view-switcher"><button className={view==='altar'?'active':''} data-testid="view-altar" onClick={()=>{setView('altar');setInfo(null);}}><Eye size={13}/>{t('The sanctuary','মণ্ডপ দর্শন')}</button><button className={view==='ritual'?'active':''} data-testid="view-ritual" onClick={()=>{setView('ritual');setInfo(null);}}><Flower2 size={13}/>{t('Watch the ritual','নিবেদন দেখুন')}</button></div>}
    {inside&&view==='ritual'&&<div className="ritual-caption" data-testid="ritual-caption"><span>{t('A GESTURE OF DEVOTION','ভক্তির নিবেদন')}</span><p>{t('The quiet rhythm of dhunuchi.','ধুনুচির নীরব ছন্দ।')}</p><small>{t('An animated, stylized interpretation.','অ্যানিমেশনে শৈল্পিক উপস্থাপনা।')}</small></div>}
   </div>
   {info&&<aside className="discovery-popup" data-testid="discovery-popup"><button data-testid="close-discovery" aria-label={t('Close discovery','বন্ধ করুন')} onClick={()=>setInfo(null)}><X size={18}/></button><span>✳ {t('A MOMENT OF DISCOVERY','আবিষ্কারের মুহূর্ত')}</span><h2 data-testid="discovery-title">{t(discoveries[info][0],discoveries[info][1])}</h2><p data-testid="discovery-description">{t(discoveries[info][2],discoveries[info][3])}</p></aside>}
   <div className="experience-bottom"><span className="canvas-help"><Move size={15}/>{t('Drag to look around','টেনে চারদিকে দেখুন')}<MousePointer2 size={15}/>{t('Scroll to zoom','স্ক্রল করে জুম করুন')}</span><div className="scene-controls"><button data-testid="toggle-pandal-lights" className={lit?'active':''} onClick={()=>setLit(!lit)} aria-pressed={lit}><Sun size={17}/>{t(lit?'Lamps on':'Lamps off',lit?'প্রদীপ জ্বলছে':'প্রদীপ নিভেছে')}</button><button data-testid="pause-sanctuary-motion" onClick={()=>setMotionEnabled(!motionEnabled)} disabled={!!reducedMotion} aria-pressed={!motionEnabled||!!reducedMotion}>{motionEnabled&&!reducedMotion?<Pause size={15}/>:<Play size={15}/>} {t(reducedMotion?'Motion reduced':motionEnabled?'Pause motion':'Resume motion',reducedMotion?'গতি সীমিত':motionEnabled?'গতি থামান':'গতি চালান')}</button><button data-testid="offer-flowers" disabled={!inside||offered||!ready} onClick={()=>{setOffered(true);if(sound)tone();}}>{offered?<Check size={17}/>:<Flower2 size={17}/>} {t(offered?'Flowers offered':'Offer flowers',offered?'ফুল নিবেদিত':'ফুল নিবেদন')}</button><button data-testid="reset-sanctuary" onClick={reset} aria-label={t('Reset sanctuary','আবার শুরু')}><RotateCcw size={17}/></button><Button className="action" data-testid="enter-pandal" onClick={enter} disabled={!ready}>{t(inside?'Step outside':'Enter the pandal',inside?'বাইরে আসুন':'মণ্ডপে প্রবেশ')}<ArrowUpRight size={17}/></Button></div></div>
  </section>
  <div className="experience-notes"><p data-testid="experience-disclaimer">{t('An artistic virtual pandal, not a scan of a real venue. The shrine uses an idol photograph within a detailed 3D space; the worshipper and offerings are stylized, symbolic interpretations.','এটি শৈল্পিক ভার্চুয়াল মণ্ডপ, বাস্তব স্থানের স্ক্যান নয়। বিস্তারিত ত্রিমাত্রিক পরিবেশে প্রতিমার ছবি রয়েছে; উপাসক ও নিবেদন শৈল্পিক এবং প্রতীকী।')}</p><span data-testid="experience-mission">{t(discovered.length===3?'You found all three stories. Take a quiet moment.':'Enter, discover three stories, and watch a quiet ritual.',discovered.length===3?'তিনটি কাহিনিই পেয়েছেন। এবার একটু শান্তিতে থাকুন।':'প্রবেশ করুন, তিনটি কাহিনি খুঁজুন এবং নিবেদন দেখুন।')}</span></div>
  <div className="sanctuary-detail-stories">{[['01','Drawn with devotion.','ভক্তিতে আঁকা।','Alpona-inspired floral patterns turn slowly like a projection of light on the floor.','মেঝেতে আলোর নকশার মতো ধীরে ঘোরে আলপনা-অনুপ্রাণিত ফুলের বৃত্ত।'],['02','A moment, made human.','মানবিক এক মুহূর্ত।','A dhoti-clad worshipper moves the dhunuchi gently; warm incense rises into the stillness.','ধুতিপরা উপাসকের হাতে ধুনুচির মৃদু দোল, প্রশান্তির মাঝে ধোঁয়া উঠে যায়।'],['03','The beauty of small things.','ছোট ছোট সৌন্দর্য।','Pleated cloth, fluted columns, marigold garlands, sweets, and the glint of a brass pradip.','কাপড়ের ভাঁজ, স্তম্ভের খাঁজ, গাঁদার মালা, মিষ্টি ও পিতলের প্রদীপের ঝিলিক।']].map(([number,en,bn,desc,db])=><article key={number} data-testid={`sanctuary-detail-${number}`}><span>{number}</span><h2>{t(en,bn)}</h2><p>{t(desc,db)}</p></article>)}</div>
 </div>;
}