import React,{useState,useEffect} from 'react';
import {ArrowLeft,ArrowRight,Expand} from 'lucide-react';
import {useApp} from '../context';
import {PageIntro,photos,Reveal} from '../components/shared';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
const images=[
 [photos.hero,'The gaze of the goddess','দেবীর দৃষ্টি','The goddess','Intricate golden adornments frame the unmistakable eyes of Maa Durga.','সোনালি অলংকারে মায়ের অনন্য দৃষ্টি।'],
 [photos.artisan,'Where devotion takes shape','শিল্পে ভক্তির রূপ','Art & craft','A handcrafted idol, surrounded by the architecture of its making.','কারুশিল্পের পরিবেশে হাতে গড়া প্রতিমা।'],
 [photos.lamps,'A thousand little prayers','অসংখ্য ছোট প্রার্থনা','Light & devotion','The gentle glow of ritual lamps, a shared language of devotion.','প্রদীপের নরম আলোয় ভক্তির ভাষা।'],
 [photos.shrine,'The divine assembly','দেবীর পরিবার','The goddess','An elaborate traditional tableau celebrates the goddess and her family.','ঐতিহ্যবাহী চালচিত্রে দেবী ও তাঁর পরিবার।'],
 [photos.pandal,'A city becomes a canvas','শহর যখন ক্যানভাস','Art & craft','Immersive festive architecture transforms everyday spaces.','উৎসবের স্থাপত্যে চেনা স্থানের রূপান্তর।'],
 [photos.night,'The stillness within','অন্তরের প্রশান্তি','Light & devotion','A moment of quiet amidst the celebration.','উৎসবের মাঝে এক শান্ত মুহূর্ত।'],
 [photos.idol,'In every tiny detail','প্রতিটি সূক্ষ্মতায়','The goddess','Patient hands and extraordinary craftsmanship in a festival idol.','প্রতিমার গায়ে ধৈর্য ও নিখুঁত কারুকাজের পরিচয়।'],
];
export default function Gallery(){const {t}=useApp();const [filter,setFilter]=useState('All'),[index,setIndex]=useState(null);const items=images.filter(i=>filter==='All'||i[3]===filter);const item=index!==null?items[index]:null;
 useEffect(()=>{const key=e=>{if(index===null)return;if(e.key==='ArrowRight')setIndex((index+1)%items.length);if(e.key==='ArrowLeft')setIndex((index+items.length-1)%items.length);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[index,items.length]);
 return <div className="gallery-page"><PageIntro chapter={t('04 / A FESTIVAL IN FRAMES','০৪ / ছবিতে উৎসব')} title={t('Some feelings','কিছু অনুভূতি')} italic={t('need no words.','ভাষার অতীত।')} description={t('The faces, the craftsmanship, the quiet in the spectacle. A photographic love letter to Pujo.','মুখ, কারুকলা ও উৎসবের মাঝের নীরবতা। পুজোকে ছবিতে লেখা ভালোবাসা।')}/><div className="gallery-toolbar"><div className="filter-tabs">{[['All','সব'],['The goddess','দেবীর রূপ'],['Art & craft','শিল্প ও কারুকলা'],['Light & devotion','আলো ও ভক্তি']].map(([en,bn],i)=><button key={en} className={filter===en?'active':''} data-testid={`gallery-filter-${i}`} onClick={()=>{setFilter(en);setIndex(null);}}>{t(en,bn)}</button>)}</div><span data-testid="gallery-count">{items.length} {t('FRAMES OF WONDER','বিস্ময়ের ছবি')}</span></div><div className="gallery-grid">{items.map((img,i)=><Reveal key={img[0]} delay={i%3*.1}><button data-testid={`gallery-image-${i}`} className="gallery-image" onClick={()=>setIndex(i)}><img src={img[0]} alt={t(img[4],img[5])} loading="lazy"/><span className="gallery-expand"><Expand size={20}/></span><div><small>{String(i+1).padStart(2,'0')}</small><h2>{t(img[1],img[2])}</h2><ArrowRight size={18}/></div></button></Reveal>)}</div><p className="fine-print" data-testid="gallery-credit">{t('Editorial festival photography via Unsplash. Images celebrate Durga Puja and are not labelled as specific 2026 pandal installations.','আনস্প্ল্যাশের উৎসবের ছবি। এগুলি ২০২৬ সালের নির্দিষ্ট মণ্ডপের ছবি হিসেবে চিহ্নিত নয়।')} <a href="https://unsplash.com/s/photos/durga-puja" target="_blank" rel="noreferrer" data-testid="gallery-photo-source">Unsplash ↗</a></p><Dialog open={item!==null} onOpenChange={open=>{if(!open)setIndex(null);}}><DialogContent className="gallery-lightbox" data-testid="gallery-lightbox">{item&&<><img src={item[0]} alt={t(item[4],item[5])}/><div className="lightbox-bottom"><div><DialogTitle data-testid="lightbox-title">{t(item[1],item[2])}</DialogTitle><DialogDescription data-testid="lightbox-description">{t(item[4],item[5])}</DialogDescription></div><div><button data-testid="gallery-previous" aria-label="Previous photo" onClick={()=>setIndex((index+items.length-1)%items.length)}><ArrowLeft/></button><span data-testid="lightbox-count">{index+1} / {items.length}</span><button data-testid="gallery-next" aria-label="Next photo" onClick={()=>setIndex((index+1)%items.length)}><ArrowRight/></button></div></div></>}</DialogContent></Dialog></div>;
}