import React,{useState} from 'react';
import {CalendarDays,Compass,Flower2,Download,Copy,TrainFront,Utensils,Heart,Phone,ArrowUpRight,Check} from 'lucide-react';
import {toast} from 'sonner';
import {useApp} from '../context';
import {PageIntro,DataState,Action} from '../components/shared';
import {Button} from '../components/ui/button';
const mantras=[
 ['Durga Pranam','দুর্গা প্রণাম','Sarva-mangala-mangalye shive sarvartha-sadhike,\nSharanye tryambake Gauri Narayani namostute.','সর্বমঙ্গলমঙ্গল্যে শিবে সর্বার্থসাধিকে।\nশরণ্যে ত্র্যম্বকে গৌরি নারায়ণি নমোস্তুতে॥','Salutations to Narayani, the auspicious one who grants refuge and fulfils worthy purposes.','সর্বমঙ্গলময়ী, আশ্রয়দায়িনী নারায়ণীকে প্রণাম।','Devi Mahatmya · Narayani Stuti'],
 ['Ya Devi · Shakti','যা দেবী · শক্তি','Ya Devi sarva-bhuteshu shakti-rupena samsthita,\nNamas tasyai, namas tasyai, namas tasyai namo namah.','যা দেবী সর্বভূতেষু শক্তিরূপেণ সংস্থিতা।\nনমস্তস্যৈ নমস্তস্যৈ নমস্তস্যৈ নমো নমঃ॥','To the goddess who abides in all beings as strength, we bow again and again.','সকল প্রাণীতে শক্তিরূপে বিরাজমান দেবীকে বারবার প্রণাম।','Devi Mahatmya · Devi Suktam'],
 ['Ya Devi · Motherhood','যা দেবী · মাতৃরূপ','Ya Devi sarva-bhuteshu matri-rupena samsthita,\nNamas tasyai, namas tasyai, namas tasyai namo namah.','যা দেবী সর্বভূতেষু মাতৃরূপেণ সংস্থিতা।\nনমস্তস্যৈ নমস্তস্যৈ নমস্তস্যৈ নমো নমঃ॥','To the goddess who abides in all beings as the mother, we offer our salutations.','সকল প্রাণীতে মাতৃরূপে বিরাজমান দেবীকে প্রণাম।','Devi Mahatmya · Devi Suktam'],
 ['Ya Devi · Peace','যা দেবী · শান্তি','Ya Devi sarva-bhuteshu shanti-rupena samsthita,\nNamas tasyai, namas tasyai, namas tasyai namo namah.','যা দেবী সর্বভূতেষু শান্তিরূপেণ সংস্থিতা।\nনমস্তস্যৈ নমস্তস্যৈ নমস্তস্যৈ নমো নমঃ॥','To the goddess who abides in all beings as peace, we bow with reverence.','সকল প্রাণীতে শান্তিরূপে বিরাজমান দেবীকে সশ্রদ্ধ প্রণাম।','Devi Mahatmya · Devi Suktam'],
 ['A simple invocation','সহজ আবাহন','Om Dum Durgaye Namah.','ওঁ দুং দুর্গায়ৈ নমঃ।','A short devotional invocation offering reverence to Goddess Durga.','দেবী দুর্গার প্রতি ভক্তি নিবেদনের সংক্ষিপ্ত মন্ত্র।','Traditional devotional mantra'],
];
export default function Guide(){const {t,dates}=useApp();const [tab,setTab]=useState('dates'),[copied,setCopied]=useState(-1);
 const download=()=>{const events=dates.map(d=>{const start=d.date.replaceAll('-','');const end=new Date(d.date+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+1);return ['BEGIN:VEVENT',`UID:${d.id}-2026@mahamaya`, 'DTSTAMP:20260101T000000Z',`DTSTART;VALUE=DATE:${start}`,`DTEND;VALUE=DATE:${end.toISOString().slice(0,10).replaceAll('-','')}`,`SUMMARY:${d.name} - Durga Puja`, 'DESCRIPTION:Planning date only. Ritual observance varies by panjika. Confirm locally.', 'END:VEVENT'].join('\r\n');});const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Mahamaya//Puja Guide//EN','CALSCALE:GREGORIAN',...events,'END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='durga-puja-2026.ics';a.click();URL.revokeObjectURL(url);toast.success(t('Calendar downloaded. Open it in your calendar app.','ক্যালেন্ডার ডাউনলোড হয়েছে। আপনার ক্যালেন্ডার অ্যাপে খুলুন।'));};
 const copy=async(m,i)=>{try{await navigator.clipboard.writeText(`${t(m[0],m[1])}\n${t(m[2],m[3])}\n${t(m[4],m[5])}`);setCopied(i);toast.success(t('Verse copied','মন্ত্র কপি হয়েছে'));}catch{toast.error(t('Please select and copy the verse manually.','মন্ত্রটি নির্বাচন করে কপি করুন।'));}};
 return <div className="guide-page"><PageIntro chapter={t('05 / YOUR HOMECOMING, MADE SIMPLE','০৫ / আপনার আগমনের সহজ নির্দেশিকা')} title={t('A little planning.','একটু পরিকল্পনা।')} italic={t('A lot of Pujo.','অনেকটা পুজো।')} description={t('The dates to remember, the rituals to understand, and the local wisdom to make every day count.','মনে রাখার দিন, বোঝার আচার ও প্রতিটি দিন উপভোগ করার স্থানীয় পরামর্শ।')}/><div className="guide-tabs">{[['dates',CalendarDays,'The 2026 calendar','২০২৬ পঞ্জিকা'],['travel',Compass,'First-timer essentials','প্রথম সফরের তথ্য'],['mantras',Flower2,'Sacred verses','পবিত্র মন্ত্র']].map(([id,Icon,en,bn])=><button key={id} data-testid={`guide-tab-${id}`} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/>{t(en,bn)}</button>)}</div>{tab==='dates'&&<section className="guide-content"><div className="guide-content-header"><h2 className="editorial-title" data-testid="calendar-heading">{t('The rhythm of','উৎসবের')} <em>{t('six sacred moments.','ছয় পবিত্র মুহূর্ত।')}</em></h2><Button className="action" data-testid="download-calendar" onClick={download} disabled={!dates.length}><Download size={16}/>{t('Save the dates','তারিখ সংরক্ষণ')}</Button></div><DataState/><div className="calendar-grid">{dates.map((d,i)=><article key={d.id} className="calendar-card" data-testid={`calendar-${d.id}`}><div className="calendar-number"><span>{d.day}</span><small>{t('OCTOBER 2026','অক্টোবর ২০২৬')}</small></div><span className="calendar-idx">0{i+1}</span><h3>{t(d.name,d.name_bn)}</h3><p>{t(d.description,d.description_bn)}</p></article>)}</div><div className="calendar-notice" data-testid="calendar-variations"><CalendarDays size={24}/><p>{t('A note on the lunar calendar: 2026 observances differ between Bengali panjikas. These are travel-planning dates, not exact puja muhurats. Shashthi and Saptami may span different civil days; confirm all ritual dates and times with your host pandal or purohit.','চন্দ্রপঞ্জিকার কথা: ২০২৬ সালে বাংলা পঞ্জিকা অনুযায়ী আচারের দিন ভিন্ন হতে পারে। এগুলি ভ্রমণ-পরিকল্পনার তারিখ, নির্দিষ্ট পূজার মুহূর্ত নয়। সমস্ত আচারের তারিখ ও সময় মণ্ডপ বা পুরোহিতের কাছে নিশ্চিত করুন।')} <a href="https://durga-puja-kolkata.com/blog/durga-puja-schedule-2026" target="_blank" rel="noreferrer" data-testid="calendar-source">{t('Read schedule reference','সময়সূচির তথ্যসূত্র')} ↗</a></p></div></section>}{tab==='travel'&&<section className="guide-content"><div className="travel-grid">{[
 [TrainFront,'Move with the city','শহরের সঙ্গে চলুন','Use the Metro for longer hops, then walk neighbourhood circuits. Festival services, road closures, and entry gates change; follow police signs and check official notices on the day.','দূরে যেতে মেট্রো, পাড়ায় পায়ে হাঁটুন। উৎসবে পরিষেবা, পথ ও গেট বদলাতে পারে; পুলিশ ও সরকারি নির্দেশিকা মেনে চলুন।'],
 [Utensils,'Taste the homecoming','উৎসবের স্বাদ নিন','Try khichuri bhog where publicly served, a Kolkata kathi roll, and mishti doi. Ask about ingredients and serving times. Carry drinking water and choose busy, clean food stalls.','সর্বসাধারণের জন্য পরিবেশিত খিচুড়ি ভোগ, কাঠি রোল ও মিষ্টি দই চেখে দেখুন। উপাদান ও সময় জেনে নিন। পানীয় জল রাখুন এবং পরিষ্কার খাবারের দোকান বাছুন।'],
 [Heart,'Arrive with respect','শ্রদ্ধা নিয়ে আসুন','Wear comfortable shoes and modest, breathable clothing. Ask before photographing worshippers or artisans. Do not touch the idol or interrupt rituals; follow footwear instructions.','আরামদায়ক জুতো ও শালীন হালকা পোশাক পরুন। দর্শনার্থী ও শিল্পীদের ছবি তোলার আগে অনুমতি নিন। প্রতিমা স্পর্শ বা আচারে বাধা দেবেন না।'],
 [Compass,'Give wonder its time','বিস্ময়ের জন্য সময় রাখুন','Plan 3–4 nearby pandals rather than crossing the city repeatedly. Mornings may be easier; evenings bring spectacular lighting and long queues. Access and step-free entry vary by venue.','বারবার শহর পার না হয়ে কাছাকাছি ৩–৪টি মণ্ডপ ঘুরুন। সকালে সুবিধা হতে পারে; সন্ধ্যায় আলো ও লম্বা লাইন। প্রবেশ ও হুইলচেয়ারের সুবিধা মণ্ডপভেদে ভিন্ন।'],
 ].map(([Icon,en,bn,desc,db],i)=><article className="travel-card" data-testid={`travel-tip-${i}`} key={en}><Icon size={26}/><h3>{t(en,bn)}</h3><p>{t(desc,db)}</p></article>)}</div><div className="emergency-bar" data-testid="emergency-info"><Phone/><div><h3>{t('Keep this close.','এই নম্বরটি রাখুন।')}</h3><p>{t('India’s integrated emergency number. Stay together, share a meeting point, and ask uniformed police for help.','ভারতের জরুরি পরিষেবার নম্বর। একসঙ্গে থাকুন, মিলিত হওয়ার স্থান ঠিক করুন, প্রয়োজনে পুলিশের সাহায্য নিন।')}</p></div><a data-testid="emergency-call" href="tel:112">112 <ArrowUpRight size={20}/></a></div><Action to="/explore" id="guide-build-trail">{t('Build your neighbourhood trail','আপনার পুজোর পথ তৈরি করুন')}</Action></section>}{tab==='mantras'&&<section className="guide-content"><p className="mantra-intro" data-testid="mantra-intro">{t('A small collection of beloved devotional verses, with accessible transliteration and meaning. This is an introduction, not a complete ritual manual; follow your family’s or priest’s tradition.','সহজ উচ্চারণ ও অর্থসহ প্রিয় কয়েকটি স্তোত্র। এটি প্রাথমিক পরিচয়, সম্পূর্ণ আচারবিধি নয়। পারিবারিক বা পুরোহিতের পরম্পরা অনুসরণ করুন।')}</p><div className="mantra-grid">{mantras.map((m,i)=><article className="mantra-card" data-testid={`mantra-${i}`} key={m[0]}><div><Flower2 size={24}/><button data-testid={`copy-mantra-${i}`} onClick={()=>copy(m,i)} aria-label="Copy verse">{copied===i?<Check size={18}/>:<Copy size={18}/>}</button></div><h3>{t(m[0],m[1])}</h3><blockquote>{t(m[2],m[3])}</blockquote><p>{t(m[4],m[5])}</p><small>{m[6]}</small></article>)}</div></section>}</div>;
}