import React, {useRef} from 'react';
import {motion,useScroll,useTransform} from 'framer-motion';
import {Link} from 'react-router-dom';
import {ArrowDown,ArrowUpRight,MapPin,Compass,Box,Headphones,CalendarDays,MoveUpRight} from 'lucide-react';
import {useApp} from '../context';
import {photos,Eyes,Reveal,Eyebrow,Action,TextLink} from '../components/shared';

const MaskLine=({children,delay=0})=><span className="mask-line"><motion.span initial={{y:'115%',rotate:2}} animate={{y:0,rotate:0}} transition={{duration:1.1,delay,ease:[.16,1,.3,1]}}>{children}</motion.span></span>;
export default function Home(){
 const {t,dates}=useApp(); const ref=useRef(); const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const y=useTransform(scrollYProgress,[0,1],[0,65]);
 return <>
 <section className="hero" ref={ref} data-testid="home-hero"><div className="hero-copy"><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.15}}><Eyebrow id="hero-eyebrow">{t('KOLKATA, WEST BENGAL · 2026','কলকাতা, পশ্চিমবঙ্গ · ২০২৬')}</Eyebrow></motion.div><h1 data-testid="hero-title"><MaskLine delay={.15}>{t('Not just a','শুধু উৎসব')}</MaskLine><MaskLine delay={.29}>{t('festival.','নয়।')}</MaskLine><MaskLine delay={.43}><em>{t('A homecoming.','মায়ের আগমন।')}</em></MaskLine></h1><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.9,duration:.8}}><p className="hero-description" data-testid="hero-description">{t('When a city becomes a canvas. When every street has a heartbeat. Come, feel the soul of Durga Puja.','যখন শহর হয়ে ওঠে শিল্পের ক্যানভাস। প্রতিটি পথে বাজে উৎসবের সুর। আসুন, অনুভব করুন দুর্গাপুজোর প্রাণ।')}</p><div className="hero-ctas"><Action to="/explore" id="hero-explore">{t('Explore the celebration','উৎসবের পথে চলুন')}</Action><Link className="round-link" to="/experience" data-testid="hero-3d"><span><Box size={20}/></span>{t('Step into a pandal','মণ্ডপে প্রবেশ করুন')}</Link></div></motion.div><div className="hero-footnote" data-testid="hero-heritage"><span className="heritage-symbol">◈</span><span>{t('DURGA PUJA IN KOLKATA','কলকাতার দুর্গাপুজো')}<small>{t('UNESCO Intangible Cultural Heritage · Inscribed 2021','ইউনেস্কো সাংস্কৃতিক ঐতিহ্য · স্বীকৃতি ২০২১')}</small></span></div></div>
 <motion.div className="hero-art" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:1.3,delay:.25}}><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><span className="art-side-caption" data-testid="hero-side-caption">{t('THE DIVINE IS IN THE DETAILS','দেবীর রূপে শিল্পের নিবেদন')}</span><div className="hero-arch"><motion.img style={{y}} src={photos.hero} alt="Maa Durga adorned with an intricately handcrafted golden crown" fetchPriority="high" data-testid="hero-idol-image"/><div className="arch-shade"/><div className="arch-caption" data-testid="hero-bengali-caption"><span>শুভ শারদীয়া</span><small>{t('MAY YOUR JOURNEY BE BLESSED','আপনার যাত্রা শুভ হোক')}</small></div></div><div className="hero-stamp" data-testid="hero-edition"><span>{t('AN IMMERSIVE','এক অনন্য')}</span><Eyes/><span>{t('BENGAL EXPERIENCE','বাংলার অভিজ্ঞতা')}</span></div><div className="art-corner"><span>22.5726° N</span><span>88.3639° E</span><i>✳</i></div></motion.div>
 <a href="#discover" className="scroll-cue" data-testid="hero-scroll"><ArrowDown size={14}/>{t('SCROLL TO FEEL IT','নিচে আরও দেখুন')}</a></section>
 <div className="festival-ribbon" data-testid="festival-ribbon"><span><i/>{t('THE CITY IS GETTING READY','শহর প্রস্তুত হচ্ছে')}</span><p>{t('Maa is coming home.','মা আসছেন।')}</p><Link to="/guide" data-testid="festival-dates-link"><CalendarDays size={16}/>{t('16—21 OCTOBER 2026','১৬—২১ অক্টোবর ২০২৬')}<ArrowUpRight size={16}/></Link></div>
 <section className="section-pad discover" id="discover"><Reveal className="section-heading"><div><Eyebrow id="discover-chapter">{t('01 / A CITY. A THOUSAND WORLDS.','০১ / এক শহর। হাজার জগৎ।')}</Eyebrow><h2 className="editorial-title" data-testid="discover-title">{t('Follow your','আপনার')} <em>{t('sense of wonder.','বিস্ময়ের পথ ধরুন।')}</em></h2></div><p data-testid="discover-description">{t('From timeless rituals to impossible artistry, there’s a little magic around every corner.','চিরন্তন আচার থেকে বিস্ময়কর শিল্প—প্রতিটি মোড়ে অপেক্ষা করছে একটুকরো জাদু।')}</p></Reveal><div className="discovery-grid">{[
 ['/explore',photos.pandal,'01',Compass,'Pandal hopping, reimagined.','পুজো পরিক্রমা, নতুন রূপে।','Find your trail through Kolkata’s extraordinary pandals.','কলকাতার অসাধারণ মণ্ডপে খুঁজে নিন আপনার পথ।','Explore the map','মানচিত্র দেখুন'],
 ['/experience',photos.shrine,'02',Box,'A little closer to the divine.','দেবীর আরও কাছে।','Walk in. Look around. A pandal that welcomes you from anywhere.','প্রবেশ করুন। ঘুরে দেখুন। যেকোনো স্থান থেকে মণ্ডপে আসুন।','Enter the 3D experience','ত্রিমাত্রিক মণ্ডপে প্রবেশ'],
 ['/music',photos.night,'03',Headphones,'The sound of belonging.','আপন হয়ে ওঠার সুর।','The songs, chants, and rhythms that bring Bengal home.','যে গান, স্তোত্র ও ছন্দে বাংলা ঘরে ফেরে।','Find your Pujo soundtrack','পুজোর সুর শুনুন']
 ].map(([url,img,n,Icon,title,bn,desc,db,cta,cb],i)=><Reveal key={url} delay={i*.12}><Link to={url} className="discovery-card" data-testid={`discover-${url.slice(1)}`}><div className="discovery-image"><img src={img} alt={title} loading="lazy"/><span className="image-number">{n}</span><span className="image-icon"><Icon size={20}/></span></div><h3>{t(title,bn)}</h3><p>{t(desc,db)}</p><span className="card-cta">{t(cta,cb)}<ArrowUpRight size={18}/></span></Link></Reveal>)}</div></section>
 <div className="marquee" aria-hidden="true"><div>{Array.from({length:4},(_,i)=><span key={i}>ART. DEVOTION. BELONGING. <b>✳</b> আসছে বছর আবার হবে <b>✳</b> </span>)}</div></div>
 <section className="story-teaser section-pad"><Reveal className="story-teaser-image"><img src={photos.artisan} alt="A handcrafted Durga idol in an artisan’s workshop" loading="lazy"/><span data-testid="craft-caption">{t('FROM RIVER CLAY TO REVERENCE','নদীর মাটি থেকে দেবীর রূপ')}</span></Reveal><Reveal className="story-teaser-copy"><Eyebrow id="story-home-chapter">{t('02 / MORE THAN MYTHOLOGY','০২ / পুরাণের পথ ধরে')}</Eyebrow><h2 className="editorial-title" data-testid="story-home-title">{t('A goddess.','এক দেবী।')}<br/>{t('A daughter.','এক কন্যা।')}<br/><em>{t('A story that lives on.','এক অমলিন কাহিনি।')}</em></h2><p data-testid="story-home-description">{t('She is strength. She is tenderness. And every autumn, she is the daughter who returns home. Discover the many stories of Maa Durga, told a little differently.','তিনি শক্তি। তিনি মমতা। প্রতি শরতে তিনি ঘরে ফেরা মেয়ে। মা দুর্গার কাহিনিগুলি জানুন একটু ভিন্নভাবে।')}</p><TextLink to="/story" id="story-home-link">{t('Let the story unfold','কাহিনির পাতায় চলুন')}</TextLink></Reveal></section>
 <section className="calendar-home section-pad"><Reveal className="section-heading"><div><Eyebrow id="dates-home-chapter">{t('03 / MARK THE MOMENTS','০৩ / শুভদিনের অপেক্ষা')}</Eyebrow><h2 className="editorial-title" data-testid="dates-home-title">{t('Some days are','কিছু দিন')} <em>{t('worth waiting for.','অপেক্ষার যোগ্য।')}</em></h2></div><TextLink to="/guide" id="home-calendar-link">{t('Your 2026 Pujo guide','আপনার ২০২৬ পুজোর নির্দেশিকা')}</TextLink></Reveal><div className="date-strip">{dates.map(d=><Link to="/guide" key={d.id} data-testid={`home-date-${d.id}`}><span>{t('OCTOBER','অক্টোবর')}</span><strong>{d.day}</strong><h3>{t(d.name,d.name_bn)}</h3><MoveUpRight size={16}/></Link>)}</div><p className="fine-print" data-testid="home-date-note">{t('Planning dates. Ritual days and timings vary by panjika; confirm with your pandal.','পরিকল্পনার তারিখ। পঞ্জিকা অনুযায়ী দিন ও সময় ভিন্ন হতে পারে; মণ্ডপে নিশ্চিত করুন।')}</p></section>
 <section className="invitation" data-testid="home-invitation"><MapPin size={26}/><p>{t('YOU DON’T HAVE TO BE FROM BENGAL TO BELONG.','বাংলার আপন হতে বাংলায় জন্মাতে হয় না।')}</p><h2>{t('Come as a visitor.','অতিথি হয়ে আসুন।')}<br/><em>{t('Leave a little Bengali.','একটু বাঙালি হয়ে ফিরুন।')}</em></h2><Action to="/guide" id="home-plan-final" light>{t('Let’s plan your homecoming','আপনার আগমনের পরিকল্পনা করুন')}</Action></section>
 </>;
}